services:
  finiex-dev:
    build: .
    container_name: finiex-testing-ide
    ports:
      - "8888:8888" # Jupyter
    volumes:
      - .:/app # Dein Code
      - ./data:/app/data # Daten-Ordner  
      - ./notebooks:/app/notebooks # Jupyter Notebooks
      # Git Konfiguration vom Host 端bernehmen
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro # SSH Keys f端r Git
    environment:
      - PYTHONPATH=/app
    stdin_open: true # F端r interaktive Shell
    tty: true # F端r interaktive Shell
    command: |
      bash -c "
        # Jupyter im Hintergrund starten
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' &
        # Container am Leben halten
        tail -f /dev/null
      "