"""
FiniexTestingIDE - Field Study Acceptance Certificate (#332)

Post-run analyzer: reads a Field Study JSONL run and emits a PASS/FAIL acceptance
certificate, mirroring the benchmark and live-adapter certificate conventions
(`release_version` / `git_commit` / `timestamp` / `valid_until` / `overall_status`,
written to a `reports/` directory, validated by a CI-friendly test).

Unlike the benchmark/live-adapter certificates (generated by pytest's session-finish),
this one is generated by the operator CLI after a live, operator-driven run.

PASS criteria (hard):
- every phase in the run reached a non-failing outcome (pass / expected_rejection / skipped /
  inconclusive — the last is a market-dependent non-fill, not a mechanical failure)
- no phase is missing a result (a missing result means the run aborted mid-sequence)
- the account is flat at session end (the broker-truth snapshot of the `session_end` PHASE —
  never simply the last one recorded, or a session-end snapshot that failed to be written
  would let the PREFLIGHT state answer the gate)

Informational (not pass-gating), each saying where it came from or that it is missing — never a
silent zero:
- `fees_charged` — what the run booked, read from the run's own report beside the capture; the sum
  of the capture's fill fees where that report is gone, unreadable or names no single currency
- `account_delta` — what the venue's account moved between the first and the session-end snapshot,
  the one figure that can contradict our booking
- `slippage` — each fill against what it is measured by: a market order against the mid when it was
  submitted, a limit against its own limit, a stop against its trigger (#566)
- `api_calls` — the session's REST calls, errors and slow calls
- `reconciliation` — whether the session reconciled, how many cycles ran or were skipped, and the
  divergences it saw
- the detected-via mix
"""

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from python.configuration.app_config_manager import AppConfigManager
from python.framework.reporting.certificates.certificate_identity_builder import (
    build_certificate_identity,
)
from python.framework.reporting.io.artifact_specs import FIELD_STUDY_CAPTURE, RUN_SUMMARY_ARTIFACT
from python.framework.reporting.io.report_artifact_io import read_artifact
from python.framework.types.log_layout_types import IO_SUBDIR
from python.framework.types.trading_env_types.order_types import OrderSide
from python.framework.utils.trading_math.slippage_math import adverse_slippage

# Default home for committed certificates — sibling of tests/live_adapters/reports
# and tests/simulation/benchmark/reports (release-gate suites).
DEFAULT_REPORTS_DIR = 'tests/live_field_study/reports'
# Certificate validity window (days) — matches the benchmark certificate backstop.
VALIDITY_DAYS = 90
# Phase outcomes that do NOT fail the certificate.
_PASSING_OUTCOMES = frozenset({'pass', 'expected_rejection', 'skipped', 'inconclusive'})
# The capture's lines that are executions — what fees and slippage are read from.
_FILL_LINES = frozenset({'order_filled', 'partial_close'})


class FieldStudyCertificate:
    """Reads a Field Study JSONL run and produces / writes a PASS/FAIL certificate."""

    @staticmethod
    def find_latest_jsonl(search_root: Optional[str] = None) -> Optional[Path]:
        """
        Find the most recent field_study.jsonl under the AutoTrader run root.

        The root is resolved from config when not given — a default literal here is a second
        declaration of a path config already owns, and it is correct only until the tree moves.

        Args:
            search_root: Directory to scan recursively; None resolves run_logs.autotrader

        Returns:
            Path to the newest field_study.jsonl, or None if none exist
        """
        root = Path(search_root) if search_root else Path(
            AppConfigManager().get_file_logging_config_object().run_logs.autotrader)
        if not root.exists():
            return None
        candidates = list(root.rglob(FIELD_STUDY_CAPTURE))
        if not candidates:
            return None
        return max(candidates, key=lambda p: p.stat().st_mtime)

    @staticmethod
    def analyze(jsonl_path: str) -> Dict[str, Any]:
        """
        Analyze a Field Study JSONL run into a result dict (no release metadata).

        Args:
            jsonl_path: Path to the run's field_study.jsonl

        Returns:
            Analysis dict (overall_status + per-phase outcomes + summaries)
        """
        header, events = FieldStudyCertificate._read(jsonl_path)
        phase_ids: List[str] = header.get('phases', [])

        results = {
            e['phase']: e for e in events if e.get('event_type') == 'phase_result'
        }

        phase_outcomes: List[Dict[str, Any]] = []
        failed: List[str] = []
        missing: List[str] = []
        for pid in phase_ids:
            result = results.get(pid)
            if result is None:
                outcome = 'missing'
                missing.append(pid)
                reason = 'phase not reached (run aborted before this phase)'
            else:
                outcome = result.get('status', 'missing')
                reason = (result.get('extra') or {}).get('reason', '')
                if outcome not in _PASSING_OUTCOMES:
                    failed.append(pid)
            phase_outcomes.append({'phase': pid, 'outcome': outcome, 'reason': reason})

        broker_snapshots = [e for e in events if e.get('event_type') == 'broker_snapshot']
        # End-state gate is "no resting orders" — a both-sided-funded study intentionally
        # holds base at the end (balances restored ~to the start), so order-book flatness
        # (no resting orders), not a zero base balance, is the criterion.
        #
        # The END snapshot is selected by PHASE, not by position. `[-1]` was the last snapshot
        # of any kind, so a session-end snapshot that never got written — every exception in
        # the shutdown try-block does that — silently promoted the PREFLIGHT snapshot, and the
        # gate then answered from the account state BEFORE the run. A gate must not pass on a
        # measurement it does not have.
        end_snapshot = next(
            (s for s in reversed(broker_snapshots) if s.get('phase') == 'session_end'),
            None,
        )
        # A read that could not see the order book carries no count (status `unread`): the gate
        # has no measurement then, and does not pass.
        end_extra = (end_snapshot.get('extra') or {}) if end_snapshot else {}
        last_order_count = end_extra.get('order_count')
        flat_at_end = last_order_count == 0

        account_delta = FieldStudyCertificate._account_delta(
            broker_snapshots, end_snapshot)

        detected_via: Dict[str, int] = {}
        for e in events:
            via = e.get('detected_via')
            if via:
                detected_via[via] = detected_via.get(via, 0) + 1

        overall = 'PASSED' if (not failed and not missing and flat_at_end) else 'FAILED'

        return {
            'profile': header.get('profile'),
            'symbol': header.get('symbol'),
            'started_utc': header.get('started_utc'),
            'overall_status': overall,
            'phase_count': len(phase_ids),
            'phases': phase_outcomes,
            'failed_phases': failed,
            'missing_phases': missing,
            'flat_at_session_end': flat_at_end,
            'fees_charged': FieldStudyCertificate._fees_charged(jsonl_path, events),
            'account_delta': account_delta,
            'slippage': FieldStudyCertificate._slippage(events),
            'api_calls': FieldStudyCertificate._api_calls(events),
            'reconciliation': FieldStudyCertificate._reconciliation(events),
            'detected_via': detected_via,
        }

    @staticmethod
    def generate(
        jsonl_path: str,
        release_version: str = 'dev',
        comment: str = '',
        reports_dir: str = DEFAULT_REPORTS_DIR,
    ) -> Path:
        """
        Analyze a run and write a PASS/FAIL certificate to the reports directory.

        Args:
            jsonl_path: Path to the run's field_study.jsonl
            release_version: Version this run certifies (or 'dev')
            comment: Optional free-text note
            reports_dir: Target directory for the certificate

        Returns:
            Path to the written certificate
        """
        analysis = FieldStudyCertificate.analyze(jsonl_path)

        identity = build_certificate_identity(
            release_version=release_version, comment=comment,
            validity_days=VALIDITY_DAYS, reports_dir=reports_dir)
        warnings = [w for w in (identity.version_mismatch(),
                                identity.dirty_tree_warning()) if w]
        certificate = {
            **identity.to_dict(),
            'source_jsonl': str(jsonl_path),
            **analysis,
        }
        # A real-money certificate that names the wrong release, or comes from uncommitted
        # work, is worse than none: the run cost money and the artifact cannot be tied to
        # the code that earned it.
        if warnings:
            certificate['overall_status'] = 'FAILED'
            certificate['warnings'] = warnings + certificate.get('warnings', [])

        reports_path = Path(reports_dir)
        reports_path.mkdir(parents=True, exist_ok=True)
        version_tag = re.sub(r'[^a-zA-Z0-9._-]', '_', release_version)
        filename = (f'field_study_report_{version_tag}_'
                    f"{identity.timestamp.strftime('%Y-%m-%d_%H%M%S')}.json")
        out_path = reports_path / filename
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(certificate, f, indent=2)

        FieldStudyCertificate._print_summary(out_path, certificate)
        return out_path

    # ============================================
    # Internals
    # ============================================

    @staticmethod
    def _fees_charged(jsonl_path: str, events: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        What the run booked in fees, read from the run's own report (#566).

        The report beside the capture carries `fees_charged` — every fee the run booked, open
        positions included. Where that report is gone, no longer reads, or names no single
        currency, the capture's fill lines carry each execution's fee and add up to the same
        bookings; the source says which was read. Neither can show a fee we computed wrong — both
        are our booking. The control is `account_delta`.

        Args:
            jsonl_path: The capture, in its run directory
            events: The capture's lines

        Returns:
            {'value', 'currency', 'source'} — source 'run_record', 'event_sum' or 'not_available'
        """
        summary_path = Path(jsonl_path).parent / IO_SUBDIR / RUN_SUMMARY_ARTIFACT.filename
        charged = []
        try:
            if summary_path.exists():
                summary = read_artifact(summary_path, RUN_SUMMARY_ARTIFACT)
                charged = [row for row in summary.currencies if row.fees_charged is not None]
        except ValueError:
            # A report written by another version of its model no longer validates — the
            # capture's own lines still add up to the same bookings.
            charged = []
        if len(charged) == 1:
            return {'value': charged[0].fees_charged, 'currency': charged[0].currency,
                    'source': 'run_record'}
        fills = [(e.get('extra') or {}) for e in events if e.get('event_type') in _FILL_LINES]
        fees = [fill['fee'] for fill in fills if fill.get('fee') is not None]
        if not fees:
            return {'value': None, 'currency': None, 'source': 'not_available'}
        currency = next((fill['fee_currency'] for fill in fills if fill.get('fee_currency')), None)
        return {'value': sum(fees), 'currency': currency, 'source': 'event_sum'}

    @staticmethod
    def _slippage(events: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Each fill against what it is measured by, per order type (#566).

        Positive is adverse. A market order is measured against the mid when it was submitted —
        the #340 measurement — a limit against its own limit, never the mid, and a stop against its
        trigger, because a triggered stop fills at the market. A fill whose reference was not
        captured counts as a leg and not as measured; a capture from before the projection carries
        no source at all and reads `not_measured`, never 0.0.

        Args:
            events: The capture's lines

        Returns:
            The slippage block: per order type what it is measured against, its legs and figures,
            the sign, and a status
        """
        legs: Dict[str, List[Optional[float]]] = {}
        measured_against: Dict[str, str] = {}
        for event in events:
            if event.get('event_type') not in _FILL_LINES:
                continue
            source = event.get('slippage') or {}
            order_type = source.get('order_type')
            if order_type is None:
                continue
            measured_against.setdefault(order_type, source.get('measured_against', 'unknown'))
            side = source.get('side')
            pct = None
            if event.get('price') is not None:
                _, pct = adverse_slippage(
                    event['price'], source.get('reference_price'),
                    OrderSide(side) if side else None)
            legs.setdefault(order_type, []).append(pct)

        by_order_type: Dict[str, Dict[str, Any]] = {}
        for order_type, values in sorted(legs.items()):
            measured = [value for value in values if value is not None]
            block: Dict[str, Any] = {'legs': len(values), 'measured': len(measured)}
            if measured and order_type == 'limit':
                block['vs_limit_max_pct'] = max(measured)
            elif measured:
                block['adverse_avg_pct'] = sum(measured) / len(measured)
                block['adverse_max_pct'] = max(measured)
            by_order_type[order_type] = block

        total = sum(block['legs'] for block in by_order_type.values())
        measured_total = sum(block['measured'] for block in by_order_type.values())
        if measured_total == 0:
            status = 'not_measured'
        elif measured_total < total:
            status = 'partly_measured'
        else:
            status = 'measured'
        return {
            'measured_against': {order_type: measured_against[order_type]
                                 for order_type in by_order_type},
            'sign': 'positive = adverse',
            'by_order_type': by_order_type,
            'status': status,
        }

    @staticmethod
    def _api_calls(events: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        The session's broker REST calls, from the telemetry written at its end (#351).

        Args:
            events: The capture's lines

        Returns:
            {'status': 'recorded', 'calls', 'errors', 'slow_calls'}, or {'status': 'not_recorded'}
        """
        line = next((e for e in reversed(events) if e.get('event_type') == 'api_perf'), None)
        if line is None:
            return {'status': 'not_recorded'}
        block = line.get('api_perf') or {}
        return {
            'status': 'recorded',
            'calls': sum(endpoint.get('calls', 0) for endpoint in block.get('endpoints', [])),
            'errors': block.get('errors', 0),
            'slow_calls': block.get('slow_calls', 0),
        }

    @staticmethod
    def _reconciliation(events: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Whether the session reconciled against the venue, and what that found (#566).

        The capture's `reconcile_alert` lines are written only when the picture CHANGED, and at
        most one per minimum interval, so their count alone cannot tell a clean session from one
        that never compared or skipped every cycle. The session's own totals, written at its end,
        can.

        Args:
            events: The capture's lines

        Returns:
            {'status': 'checked' | 'partly_skipped' | 'skipped' | 'not_run' | 'disabled' |
            'not_recorded', ...} with the cycles, skipped cycles and divergences seen where
            recorded, and the divergent pictures the capture holds
        """
        divergent_records = sum(
            1 for e in events
            if e.get('event_type') == 'reconcile_alert' and e.get('status') == 'divergent')
        line = next((e for e in reversed(events) if e.get('event_type') == 'reconcile_summary'),
                    None)
        if line is None:
            return {'status': 'not_recorded', 'divergent_records': divergent_records}
        summary = line.get('reconcile') or {}
        if not summary.get('enabled'):
            return {'status': 'disabled'}
        cycles = summary.get('cycles', 0)
        skipped = summary.get('skipped', 0)
        if cycles == 0:
            status = 'not_run'
        elif skipped >= cycles:
            status = 'skipped'
        elif skipped:
            status = 'partly_skipped'
        else:
            status = 'checked'
        return {
            'status': status,
            'cycles': cycles,
            'skipped': skipped,
            'divergences_seen': summary.get('divergences_seen', 0),
            'divergent_records': divergent_records,
        }

    @staticmethod
    def _account_delta(
        broker_snapshots: List[Dict[str, Any]],
        end_snapshot: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        What the ACCOUNT moved between the first snapshot and the session-end one (#506).

        The venue-side counterpart to `fees_charged`: one figure is our booking, the other is
        the account, and their DIFFERENCE is how well we model the venue — which is the
        question the certificate exists to answer. It is a MEASUREMENT, never a gate: a cost
        the run cannot explain must be visible, not fatal.

        `status` is part of the answer rather than an afterthought. An absent or unreadable
        snapshot has to say so, because a silent empty delta reads as "nothing moved" — the
        exact failure a cost figure of zero already had.

        Args:
            broker_snapshots: Every broker-truth snapshot of the run, in order
            end_snapshot: The session-end snapshot, or None when it was never written

        Returns:
            {'status': ..., 'per_asset': {asset: delta}} — `per_asset` empty unless 'ok'
        """
        if not broker_snapshots or end_snapshot is None:
            return {'status': 'no_end_snapshot', 'per_asset': {}}
        if broker_snapshots[0] is end_snapshot:
            return {'status': 'single_snapshot', 'per_asset': {}}

        start_balances = (broker_snapshots[0].get('extra') or {}).get('balances')
        end_balances = (end_snapshot.get('extra') or {}).get('balances')
        if start_balances is None or end_balances is None:
            return {'status': 'balances_unreadable', 'per_asset': {}}

        # An asset listed on one side only appeared or vanished — that is a movement from or
        # to zero, not a reason to drop it.
        per_asset = {}
        for asset in sorted(set(start_balances) | set(end_balances)):
            moved = float(end_balances.get(asset, 0.0) or 0.0) - float(
                start_balances.get(asset, 0.0) or 0.0)
            if moved:
                per_asset[asset] = moved
        return {'status': 'ok', 'per_asset': per_asset}

    @staticmethod
    def _print_summary(out_path: Path, cert: Dict[str, Any]) -> None:
        """Print a concise operator-facing certificate summary."""
        status = cert['overall_status']
        mark = '✅' if status == 'PASSED' else '❌'
        print(f"\n{'=' * 60}")
        print(f'  {mark} FIELD STUDY CERTIFICATE — {status}')
        print(f"  release: {cert['release_version']}  |  commit: {cert['git_commit']}")
        print(f"  profile: {cert['profile']}  |  symbol: {cert['symbol']}")
        print(f"  phases: {cert['phase_count']}  |  flat at end: {cert['flat_at_session_end']}")
        if cert['failed_phases']:
            print(f"  failed:  {cert['failed_phases']}")
        if cert['missing_phases']:
            print(f"  missing: {cert['missing_phases']}")
        # The source is printed beside the figure: a total read from the run's report and one
        # added up from the capture are the same bookings, but only the first is the run's own.
        fees = cert.get('fees_charged') or {}
        if fees.get('value') is None:
            print('  fees charged: not available')
        else:
            print(f"  fees charged: {fees['value']:.6f} {fees.get('currency') or ''} "
                  f"({fees.get('source')})")
        # The account's own movement beside our booking — a missing measurement is printed
        # as such rather than as a silent absence.
        delta = cert.get('account_delta') or {}
        if delta.get('status') == 'ok':
            moved = '  '.join(
                f'{asset} {amount:+.8f}' for asset, amount in delta['per_asset'].items())
            print(f"  account delta: {moved or 'nothing moved'}")
        else:
            print(f"  account delta: {delta.get('status', 'unknown')}")
        slippage = cert.get('slippage') or {}
        parts = []
        for order_type, block in (slippage.get('by_order_type') or {}).items():
            if 'vs_limit_max_pct' in block:
                parts.append(f"{order_type} max {block['vs_limit_max_pct']:+.4f}% vs limit "
                             f"({block['measured']}/{block['legs']})")
            elif 'adverse_max_pct' in block:
                parts.append(f"{order_type} avg {block['adverse_avg_pct']:+.4f}% "
                             f"max {block['adverse_max_pct']:+.4f}% "
                             f"({block['measured']}/{block['legs']})")
            else:
                parts.append(f"{order_type} not measured ({block['legs']} legs)")
        print(f"  slippage: {slippage.get('status', 'not_measured')}"
              + (f" — {' · '.join(parts)}" if parts else ''))
        reconciliation = cert.get('reconciliation') or {}
        if 'cycles' in reconciliation:
            print(f"  reconciliation: {reconciliation['status']} — {reconciliation['cycles']} "
                  f"cycles, {reconciliation['skipped']} skipped, "
                  f"{reconciliation['divergences_seen']} divergences seen")
        else:
            print(f"  reconciliation: {reconciliation.get('status', 'not_recorded')}")
        api = cert.get('api_calls') or {}
        if api.get('status') == 'recorded':
            print(f"  api: {api['calls']} calls, {api['errors']} errors, {api['slow_calls']} slow")
        print(f'  certificate: {out_path}')
        print(f"{'=' * 60}\n")

    @staticmethod
    def _read(jsonl_path: str) -> tuple:
        """Read a JSONL run into (header, events). Raises on an empty file."""
        path = Path(jsonl_path)
        lines = [ln for ln in path.read_text(encoding='utf-8').splitlines() if ln.strip()]
        if not lines:
            raise ValueError(f'Field Study JSONL is empty: {jsonl_path}')
        header = json.loads(lines[0])
        events = [json.loads(ln) for ln in lines[1:]]
        return header, events
