"""
FiniexTestingIDE - Field Study Acceptance Certificate (#332)

Post-run analyzer: reads a Field Study JSONL run and emits a PASS/FAIL acceptance
certificate, mirroring the benchmark and live-adapter certificate conventions
(`release_version` / `git_commit` / `timestamp` / `valid_until` / `overall_status`,
written to a `reports/` directory, validated by a CI-friendly test).

Unlike the benchmark/live-adapter certificates (generated by pytest's session-finish),
this one is generated by the operator CLI after a live, operator-driven run.

PASS criteria (hard):
- every phase in the run reached a non-failing outcome (pass / expected_rejection / skipped /
  inconclusive — the last is a market-dependent non-fill, not a mechanical failure)
- no phase is missing a result (a missing result means the run aborted mid-sequence)
- the account is flat at session end (the broker-truth snapshot of the `session_end` PHASE —
  never simply the last one recorded, or a session-end snapshot that failed to be written
  would let the PREFLIGHT state answer the gate)

Informational (not pass-gating): realized cost (read from the run's own stamp, with its
source named — a reconstruction from per-event commissions cannot see a full close), the
account delta (venue-side movement between the first and the session-end snapshot, which is
the only figure that can contradict our booking), slippage distribution, detected-via mix,
reconciliation alert count.
"""

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from python.configuration.app_config_manager import AppConfigManager
from python.framework.reporting.certificates.certificate_identity_builder import (
    build_certificate_identity,
)

# Default home for committed certificates — sibling of tests/live_adapters/reports
# and tests/simulation/benchmark/reports (release-gate suites).
DEFAULT_REPORTS_DIR = 'tests/live_field_study/reports'
# Certificate validity window (days) — matches the benchmark certificate backstop.
VALIDITY_DAYS = 90
# Phase outcomes that do NOT fail the certificate.
_PASSING_OUTCOMES = frozenset({'pass', 'expected_rejection', 'skipped', 'inconclusive'})


class FieldStudyCertificate:
    """Reads a Field Study JSONL run and produces / writes a PASS/FAIL certificate."""

    @staticmethod
    def find_latest_jsonl(search_root: Optional[str] = None) -> Optional[Path]:
        """
        Find the most recent field_study.jsonl under the AutoTrader run root.

        The root is resolved from config when not given — a default literal here is a second
        declaration of a path config already owns, and it is correct only until the tree moves.

        Args:
            search_root: Directory to scan recursively; None resolves run_logs.live

        Returns:
            Path to the newest field_study.jsonl, or None if none exist
        """
        root = Path(search_root) if search_root else Path(
            AppConfigManager().get_file_logging_config_object().run_logs.live)
        if not root.exists():
            return None
        candidates = list(root.rglob('field_study.jsonl'))
        if not candidates:
            return None
        return max(candidates, key=lambda p: p.stat().st_mtime)

    @staticmethod
    def analyze(jsonl_path: str) -> Dict[str, Any]:
        """
        Analyze a Field Study JSONL run into a result dict (no release metadata).

        Args:
            jsonl_path: Path to the run's field_study.jsonl

        Returns:
            Analysis dict (overall_status + per-phase outcomes + summaries)
        """
        header, events = FieldStudyCertificate._read(jsonl_path)
        phase_ids: List[str] = header.get('phases', [])

        results = {
            e['phase']: e for e in events if e.get('event_type') == 'phase_result'
        }

        phase_outcomes: List[Dict[str, Any]] = []
        failed: List[str] = []
        missing: List[str] = []
        for pid in phase_ids:
            result = results.get(pid)
            if result is None:
                outcome = 'missing'
                missing.append(pid)
                reason = 'phase not reached (run aborted before this phase)'
            else:
                outcome = result.get('status', 'missing')
                reason = (result.get('extra') or {}).get('reason', '')
                if outcome not in _PASSING_OUTCOMES:
                    failed.append(pid)
            phase_outcomes.append({'phase': pid, 'outcome': outcome, 'reason': reason})

        broker_snapshots = [e for e in events if e.get('event_type') == 'broker_snapshot']
        # End-state gate is "no resting orders" — a both-sided-funded study intentionally
        # holds base at the end (balances restored ~to the start), so order-book flatness
        # (no resting orders), not a zero base balance, is the criterion.
        #
        # The END snapshot is selected by PHASE, not by position. `[-1]` was the last snapshot
        # of any kind, so a session-end snapshot that never got written — every exception in
        # the shutdown try-block does that — silently promoted the PREFLIGHT snapshot, and the
        # gate then answered from the account state BEFORE the run. A gate must not pass on a
        # measurement it does not have.
        end_snapshot = next(
            (s for s in reversed(broker_snapshots) if s.get('phase') == 'session_end'),
            None,
        )
        last_order_count = (
            (end_snapshot.get('extra') or {}).get('order_count', 1)
            if end_snapshot else 1
        )
        flat_at_end = end_snapshot is not None and last_order_count == 0

        account_delta = FieldStudyCertificate._account_delta(
            broker_snapshots, end_snapshot)

        reconcile_alerts = [e for e in events if e.get('event_type') == 'reconcile_alert']

        # The run stamps its own total (#506). Summing the per-event `commission` values is
        # only a fallback, and a KNOWN-partial one: a FULL close emits no decision event, so
        # the reconstruction misses every full-close leg. `realized_cost_source` says which
        # of the two the number is, because a partial figure that looks authoritative is the
        # failure this field already had — four certificates recorded 0.
        stamped = next(
            (e for e in reversed(events) if e.get('event_type') == 'session_cost'), None)
        if stamped is not None:
            extra = stamped.get('extra') or {}
            realized_cost = float(extra.get('realized_cost', 0.0) or 0.0)
            realized_cost_source = extra.get('source', 'session_cost')
        else:
            commissions = [
                (e.get('extra') or {}).get('commission', 0.0)
                for e in events if e.get('event_type') in ('order_filled', 'partial_close')
            ]
            realized_cost = sum(c for c in commissions if c)
            realized_cost_source = 'event_sum_partial'

        slip_points = [
            (e.get('slippage') or {}).get('slippage_points')
            for e in events if e.get('slippage')
        ]
        slip_points = [s for s in slip_points if s is not None]

        detected_via: Dict[str, int] = {}
        for e in events:
            via = e.get('detected_via')
            if via:
                detected_via[via] = detected_via.get(via, 0) + 1

        overall = 'PASSED' if (not failed and not missing and flat_at_end) else 'FAILED'

        return {
            'profile': header.get('profile'),
            'symbol': header.get('symbol'),
            'started_utc': header.get('started_utc'),
            'overall_status': overall,
            'phase_count': len(phase_ids),
            'phases': phase_outcomes,
            'failed_phases': failed,
            'missing_phases': missing,
            'flat_at_session_end': flat_at_end,
            'account_delta': account_delta,
            'realized_cost': realized_cost,
            'realized_cost_source': realized_cost_source,
            'slippage_points': {
                'count': len(slip_points),
                'max': max(slip_points) if slip_points else 0.0,
                'avg': (sum(slip_points) / len(slip_points)) if slip_points else 0.0,
            },
            'detected_via': detected_via,
            'reconcile_alert_count': len(reconcile_alerts),
        }

    @staticmethod
    def generate(
        jsonl_path: str,
        release_version: str = 'dev',
        comment: str = '',
        reports_dir: str = DEFAULT_REPORTS_DIR,
    ) -> Path:
        """
        Analyze a run and write a PASS/FAIL certificate to the reports directory.

        Args:
            jsonl_path: Path to the run's field_study.jsonl
            release_version: Version this run certifies (or 'dev')
            comment: Optional free-text note
            reports_dir: Target directory for the certificate

        Returns:
            Path to the written certificate
        """
        analysis = FieldStudyCertificate.analyze(jsonl_path)

        identity = build_certificate_identity(
            release_version=release_version, comment=comment,
            validity_days=VALIDITY_DAYS, reports_dir=reports_dir)
        warnings = [w for w in (identity.version_mismatch(),
                                identity.dirty_tree_warning()) if w]
        certificate = {
            **identity.to_dict(),
            'source_jsonl': str(jsonl_path),
            **analysis,
        }
        # A real-money certificate that names the wrong release, or comes from uncommitted
        # work, is worse than none: the run cost money and the artifact cannot be tied to
        # the code that earned it.
        if warnings:
            certificate['overall_status'] = 'FAILED'
            certificate['warnings'] = warnings + certificate.get('warnings', [])

        reports_path = Path(reports_dir)
        reports_path.mkdir(parents=True, exist_ok=True)
        version_tag = re.sub(r'[^a-zA-Z0-9._-]', '_', release_version)
        filename = (f'field_study_report_{version_tag}_'
                    f"{identity.timestamp.strftime('%Y-%m-%d_%H%M%S')}.json")
        out_path = reports_path / filename
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(certificate, f, indent=2)

        FieldStudyCertificate._print_summary(out_path, certificate)
        return out_path

    # ============================================
    # Internals
    # ============================================

    @staticmethod
    def _account_delta(
        broker_snapshots: List[Dict[str, Any]],
        end_snapshot: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        What the ACCOUNT moved between the first snapshot and the session-end one (#506).

        The venue-side counterpart to `realized_cost`: one figure is our booking, the other
        is the account, and their DIFFERENCE is how well we model the venue — which is the
        question the certificate exists to answer. It is a MEASUREMENT, never a gate: a cost
        the run cannot explain must be visible, not fatal.

        `status` is part of the answer rather than an afterthought. An absent or unreadable
        snapshot has to say so, because a silent empty delta reads as "nothing moved" — the
        exact failure a `realized_cost` of zero already had.

        Args:
            broker_snapshots: Every broker-truth snapshot of the run, in order
            end_snapshot: The session-end snapshot, or None when it was never written

        Returns:
            {'status': ..., 'per_asset': {asset: delta}} — `per_asset` empty unless 'ok'
        """
        if not broker_snapshots or end_snapshot is None:
            return {'status': 'no_end_snapshot', 'per_asset': {}}
        if broker_snapshots[0] is end_snapshot:
            return {'status': 'single_snapshot', 'per_asset': {}}

        start_balances = (broker_snapshots[0].get('extra') or {}).get('balances')
        end_balances = (end_snapshot.get('extra') or {}).get('balances')
        if start_balances is None or end_balances is None:
            return {'status': 'balances_unreadable', 'per_asset': {}}

        # An asset listed on one side only appeared or vanished — that is a movement from or
        # to zero, not a reason to drop it.
        per_asset = {}
        for asset in sorted(set(start_balances) | set(end_balances)):
            moved = float(end_balances.get(asset, 0.0) or 0.0) - float(
                start_balances.get(asset, 0.0) or 0.0)
            if moved:
                per_asset[asset] = moved
        return {'status': 'ok', 'per_asset': per_asset}

    @staticmethod
    def _print_summary(out_path: Path, cert: Dict[str, Any]) -> None:
        """Print a concise operator-facing certificate summary."""
        status = cert['overall_status']
        mark = '✅' if status == 'PASSED' else '❌'
        print(f"\n{'=' * 60}")
        print(f'  {mark} FIELD STUDY CERTIFICATE — {status}')
        print(f"  release: {cert['release_version']}  |  commit: {cert['git_commit']}")
        print(f"  profile: {cert['profile']}  |  symbol: {cert['symbol']}")
        print(f"  phases: {cert['phase_count']}  |  flat at end: {cert['flat_at_session_end']}")
        if cert['failed_phases']:
            print(f"  failed:  {cert['failed_phases']}")
        if cert['missing_phases']:
            print(f"  missing: {cert['missing_phases']}")
        # The source is printed beside the figure on purpose: a reconstructed total is
        # known-partial (it cannot see a full close), and a partial number that looks
        # authoritative is the failure this field already had.
        # Only the FALLBACK is flagged. Which stamp produced an authoritative figure is
        # provenance and travels in the field; what the reader has to see at a glance is
        # whether the number was READ or RECONSTRUCTED — the reconstruction cannot see a
        # full close, so it is always an undercount.
        source = cert.get('realized_cost_source', 'event_sum_partial')
        source_tag = '  [reconstructed — partial]' if source == 'event_sum_partial' else ''
        print(
            f"  realized cost: {cert['realized_cost']:.6f}{source_tag}  "
            f"|  reconcile alerts: {cert['reconcile_alert_count']}"
        )
        # The account's own movement beside our booking — a missing measurement is printed
        # as such rather than as a silent absence.
        delta = cert.get('account_delta') or {}
        if delta.get('status') == 'ok':
            moved = '  '.join(
                f'{asset} {amount:+.8f}' for asset, amount in delta['per_asset'].items())
            print(f"  account delta: {moved or 'nothing moved'}")
        else:
            print(f"  account delta: {delta.get('status', 'unknown')}")
        print(f'  certificate: {out_path}')
        print(f"{'=' * 60}\n")

    @staticmethod
    def _read(jsonl_path: str) -> tuple:
        """Read a JSONL run into (header, events). Raises on an empty file."""
        path = Path(jsonl_path)
        lines = [ln for ln in path.read_text(encoding='utf-8').splitlines() if ln.strip()]
        if not lines:
            raise ValueError(f'Field Study JSONL is empty: {jsonl_path}')
        header = json.loads(lines[0])
        events = [json.loads(ln) for ln in lines[1:]]
        return header, events
