"""
FiniexTestingIDE - Field Study Acceptance Certificate (#332)

Post-run analyzer: reads a Field Study JSONL run and emits a PASS/FAIL acceptance
certificate, mirroring the benchmark and live-adapter certificate conventions
(`release_version` / `git_commit` / `timestamp` / `valid_until` / `overall_status`,
written to a `reports/` directory, validated by a CI-friendly test).

Unlike the benchmark/live-adapter certificates (generated by pytest's session-finish),
this one is generated by the operator CLI after a live, operator-driven run.

PASS criteria (hard):
- every phase in the run reached a non-failing outcome (pass / expected_rejection / skipped /
  inconclusive — the last is a market-dependent non-fill, not a mechanical failure)
- no phase is missing a result (a missing result means the run aborted mid-sequence)
- the account is flat at session end (last broker-truth snapshot)

Informational (not pass-gating): realized cost, slippage distribution, detected-via mix,
reconciliation alert count.
"""

import json
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from python.framework.utils.git_info_utils import get_git_commit

# Default home for committed certificates — sibling of tests/live_adapters/reports
# and tests/simulation/benchmark/reports (release-gate suites).
DEFAULT_REPORTS_DIR = 'tests/live_field_study/reports'
# Certificate validity window (days) — matches the benchmark certificate backstop.
VALIDITY_DAYS = 90
# Phase outcomes that do NOT fail the certificate.
_PASSING_OUTCOMES = frozenset({'pass', 'expected_rejection', 'skipped', 'inconclusive'})


class FieldStudyCertificate:
    """Reads a Field Study JSONL run and produces / writes a PASS/FAIL certificate."""

    @staticmethod
    def find_latest_jsonl(search_root: str = 'logs/autotrader') -> Optional[Path]:
        """
        Find the most recent field_study.jsonl under the AutoTrader log root.

        Args:
            search_root: Directory to scan recursively

        Returns:
            Path to the newest field_study.jsonl, or None if none exist
        """
        root = Path(search_root)
        if not root.exists():
            return None
        candidates = list(root.rglob('field_study.jsonl'))
        if not candidates:
            return None
        return max(candidates, key=lambda p: p.stat().st_mtime)

    @staticmethod
    def analyze(jsonl_path: str) -> Dict[str, Any]:
        """
        Analyze a Field Study JSONL run into a result dict (no release metadata).

        Args:
            jsonl_path: Path to the run's field_study.jsonl

        Returns:
            Analysis dict (overall_status + per-phase outcomes + summaries)
        """
        header, events = FieldStudyCertificate._read(jsonl_path)
        phase_ids: List[str] = header.get('phases', [])

        results = {
            e['phase']: e for e in events if e.get('event_type') == 'phase_result'
        }

        phase_outcomes: List[Dict[str, Any]] = []
        failed: List[str] = []
        missing: List[str] = []
        for pid in phase_ids:
            result = results.get(pid)
            if result is None:
                outcome = 'missing'
                missing.append(pid)
                reason = 'phase not reached (run aborted before this phase)'
            else:
                outcome = result.get('status', 'missing')
                reason = (result.get('extra') or {}).get('reason', '')
                if outcome not in _PASSING_OUTCOMES:
                    failed.append(pid)
            phase_outcomes.append({'phase': pid, 'outcome': outcome, 'reason': reason})

        broker_snapshots = [e for e in events if e.get('event_type') == 'broker_snapshot']
        # End-state gate is "no resting orders" — a both-sided-funded study intentionally
        # holds base at the end (balances restored ~to the start), so order-book flatness
        # (no resting orders), not a zero base balance, is the criterion.
        last_order_count = (
            (broker_snapshots[-1].get('extra') or {}).get('order_count', 1)
            if broker_snapshots else 1
        )
        flat_at_end = bool(broker_snapshots) and last_order_count == 0

        reconcile_alerts = [e for e in events if e.get('event_type') == 'reconcile_alert']

        commissions = [
            (e.get('extra') or {}).get('commission', 0.0)
            for e in events if e.get('event_type') in ('order_filled', 'partial_close')
        ]
        realized_cost = sum(c for c in commissions if c)

        slip_points = [
            (e.get('slippage') or {}).get('slippage_points')
            for e in events if e.get('slippage')
        ]
        slip_points = [s for s in slip_points if s is not None]

        detected_via: Dict[str, int] = {}
        for e in events:
            via = e.get('detected_via')
            if via:
                detected_via[via] = detected_via.get(via, 0) + 1

        overall = 'PASSED' if (not failed and not missing and flat_at_end) else 'FAILED'

        return {
            'profile': header.get('profile'),
            'symbol': header.get('symbol'),
            'started_utc': header.get('started_utc'),
            'overall_status': overall,
            'phase_count': len(phase_ids),
            'phases': phase_outcomes,
            'failed_phases': failed,
            'missing_phases': missing,
            'flat_at_session_end': flat_at_end,
            'realized_cost': realized_cost,
            'slippage_points': {
                'count': len(slip_points),
                'max': max(slip_points) if slip_points else 0.0,
                'avg': (sum(slip_points) / len(slip_points)) if slip_points else 0.0,
            },
            'detected_via': detected_via,
            'reconcile_alert_count': len(reconcile_alerts),
        }

    @staticmethod
    def generate(
        jsonl_path: str,
        release_version: str = 'dev',
        comment: str = '',
        reports_dir: str = DEFAULT_REPORTS_DIR,
    ) -> Path:
        """
        Analyze a run and write a PASS/FAIL certificate to the reports directory.

        Args:
            jsonl_path: Path to the run's field_study.jsonl
            release_version: Version this run certifies (or 'dev')
            comment: Optional free-text note
            reports_dir: Target directory for the certificate

        Returns:
            Path to the written certificate
        """
        analysis = FieldStudyCertificate.analyze(jsonl_path)

        now = datetime.now(timezone.utc)
        certificate = {
            'record_kind': 'certificate',
            'release_version': release_version,
            'git_commit': get_git_commit() or 'unknown',
            'timestamp': now.isoformat(),
            'valid_until': (now + timedelta(days=VALIDITY_DAYS)).isoformat(),
            'comment': comment,
            'source_jsonl': str(jsonl_path),
            **analysis,
        }

        reports_path = Path(reports_dir)
        reports_path.mkdir(parents=True, exist_ok=True)
        version_tag = re.sub(r'[^a-zA-Z0-9._-]', '_', release_version)
        filename = f"field_study_report_{version_tag}_{now.strftime('%Y-%m-%d_%H%M%S')}.json"
        out_path = reports_path / filename
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(certificate, f, indent=2)

        FieldStudyCertificate._print_summary(out_path, certificate)
        return out_path

    # ============================================
    # Internals
    # ============================================

    @staticmethod
    def _print_summary(out_path: Path, cert: Dict[str, Any]) -> None:
        """Print a concise operator-facing certificate summary."""
        status = cert['overall_status']
        mark = '✅' if status == 'PASSED' else '❌'
        print(f"\n{'=' * 60}")
        print(f"  {mark} FIELD STUDY CERTIFICATE — {status}")
        print(f"  release: {cert['release_version']}  |  commit: {cert['git_commit']}")
        print(f"  profile: {cert['profile']}  |  symbol: {cert['symbol']}")
        print(f"  phases: {cert['phase_count']}  |  flat at end: {cert['flat_at_session_end']}")
        if cert['failed_phases']:
            print(f"  failed:  {cert['failed_phases']}")
        if cert['missing_phases']:
            print(f"  missing: {cert['missing_phases']}")
        print(
            f"  realized cost: {cert['realized_cost']:.6f}  "
            f"|  reconcile alerts: {cert['reconcile_alert_count']}"
        )
        print(f"  certificate: {out_path}")
        print(f"{'=' * 60}\n")

    @staticmethod
    def _read(jsonl_path: str) -> tuple:
        """Read a JSONL run into (header, events). Raises on an empty file."""
        path = Path(jsonl_path)
        lines = [ln for ln in path.read_text(encoding='utf-8').splitlines() if ln.strip()]
        if not lines:
            raise ValueError(f"Field Study JSONL is empty: {jsonl_path}")
        header = json.loads(lines[0])
        events = [json.loads(ln) for ln in lines[1:]]
        return header, events
